version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi_app
    env_file: ./fastapi_app/.env
    expose:
      - "8000"

  telegram_bot:
    build:
      context: ./telegram_bot
    env_file: ./telegram_bot/.env
    depends_on:
      - nginx

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi

volumes:
  mongo_data: